name: Consoldate ASTICI issues into a single  report
on:
  workflow_dispatch:
#
#    - cron : '20 0 * * *'
jobs:
  Report_gen:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name : consolidate ASTICI issues
        id: ASTICI-report-gen
        uses: actions/checkout@v2
        with:
          repository: issue2report/issue2report
          # Shallow clones should be disabled for a better relevancy of analysis
          fetch-depth: 0
      - name: run PDF report generator with issue2report
        run: |
            echo ${{secrets.GITHUB_TOKEN}} >> ./token
            pip install --upgrade pip
            pip install -r requirements.txt
            python3 issue2report.py -t default -gu pradyumna-muppirala -gr ASTICI_pentest_report
#      - name: install pip dependencies
#       id: pip_dependecy_installations
#        run: |
#         pip install seaborn
              
#      - name: consolidate ASTICI issues
#       id: ASTICI-report-gen
#       uses: gramster/github-issue-reporter@main
#       with:
#          repository: pradyumna-muppirala/ASTICI
#         githubToken: ${{ secrets.GITHUB_TOKEN }}
#         days: 7
#         all: false
#         reportNameTemplate: "ASTICI-Issues-rpt-%A.md"

