name: Consoldate ASTICI issues into a single  report
on:
  workflow_dispatch:
#
#    - cron : '20 0 * * *'
jobs:
  Report_gen:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name : consolidate ASTICI issues
        id: ASTICI-report-gen
        run: |
          npm install -g github-issue-reports
          github-issue-reports -o pradyumna-muppirala -r ASTICI -t ${{ secrets.GITHUB_TOKEN }}
          
#      - name: install pip dependencies
#       id: pip_dependecy_installations
#        run: |
#         pip install seaborn
              
#      - name: consolidate ASTICI issues
#       id: ASTICI-report-gen
#       uses: gramster/github-issue-reporter@main
#       with:
#          repository: pradyumna-muppirala/ASTICI
#         githubToken: ${{ secrets.GITHUB_TOKEN }}
#         days: 7
#         all: false
#         reportNameTemplate: "ASTICI-Issues-rpt-%A.md"

