name: Consoldate ASTICI issues into a single  report
on:
  workflow_dispatch:
#
#    - cron : '20 0 * * *'
jobs:
  Report_gen:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name : consolidate ASTICI issues
        id: ASTICI-report-gen
        run: |
            git clone https://github.com/RafyAmgadBenjamin/ghreport.git
            pip install --upgrade pip
            ls
            pwd
            pip install -r requirements.txt
            ls
            outputfname = "ASTICIIssueRpt-$DAY_OF_WEEK.md"
            echo $outputfname
            python3 main.py --key ${{ secrets.GITHUB_TOKEN }} --dest ./reports/$outputfname --account pradyumna=muppirala --ndays 5
            git add ./reports/$outputfname
            git push
#      - name: install pip dependencies
#       id: pip_dependecy_installations
#        run: |
#         pip install seaborn
              
#      - name: consolidate ASTICI issues
#       id: ASTICI-report-gen
#       uses: gramster/github-issue-reporter@main
#       with:
#          repository: pradyumna-muppirala/ASTICI
#         githubToken: ${{ secrets.GITHUB_TOKEN }}
#         days: 7
#         all: false
#         reportNameTemplate: "ASTICI-Issues-rpt-%A.md"

