name: Consoldate ASTICI issues into a single  report
on:
  workflow_dispatch:
  schedule: 
  - cron : '20 0 * * *'
jobs:
  Report_gen:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
    
      - name: install pip dependencies
        id: pip_dependecy_installations
        run: |
          pip install seaborn
          pip install seaborn[stats]
              
      - name: consolidate ASTICI issues
        id: ASTICI-report-gen
        uses: gramster/github-issue-reporter@main
        with:
          repository: pradyumna-muppirala/ASTICI
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          days: 7
          all: false
          reportNameTemplate: "ASTICI-Issues-rpt-%A.md"

