name: Consoldate ASTICI issues into a single  report
on:
  schedule: 
  - cron : '0 0 * * *'
jobs:
  Report_gen:
    runs-on: ubuntu-latest
    steps:
    - name: consolidate ASTICI issues
      id: report-gen
      uses: gramster/github-issue-reporter@main
      with:
        repository: pradyumna-muppirala/ASTICI
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        days: 7
        all: false
        reportNameTemplate: "ASTICI-Issues-rpt-%A.md"

