name: Consoldate ASTICI issues into a single  report
on:
  schedule: 
  - cron : '0 0 * * *'
jobs:
  runs-on: ubuntu-latest
  timeout-minutes: 10
  steps:
    name: consolidate ASTICI issues
    uses: gramster/github-issue-reporter@main
    with:
      repository: pradyumna-muppirala/ASTICI
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      days: 7
      all: false
      reportNameTemplate: "ASTICI-Issues-rpt-%A.md"

